covid/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls')),
    path('pollpage/',include('pollster.urls')),
]


landingpage/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name='landingpage'

urlpatterns = [
    path('',views.home,name='home'),
]

pollster/urls.py
from django.urls import path
from . import views

app_name='polls'

urlpatterns=[
    path('',views.pollpage,name='pollpage'),
    path('<int:qn_id>/',views.details,name='details'),
    path('<int:qn_id>/results/',views.results,name='results'),
    path('<int:qn_id>/vote/',views.vote,name='vote'),
    path('resultsdata/<str:obj>/',views.resultsdata,name='resultsdata'),
]

landingpage/models.py
from django.db import models

# Create your models here.

pollster/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date      = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question      = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text   = models.CharField(max_length=300)
    votes         = models.IntegerField(default=0)

    def  __str__(self):
        return self.choice_text

landingpage/views.py
from django.shortcuts import render
import requests

def home(request):
    if 'country' in request.GET:
        response_worldwide = requests.get('https://covid19.mathdro.id/api')
        data_worldwide = response_worldwide.json()
        confirmed_worldwide = data_worldwide['confirmed']
        recovered_worldwide = data_worldwide['recovered']
        deaths_worldwide = data_worldwide['deaths']
        country_name = {}
        country_name = request.GET['country']
        country_name = country_name.title()
        url1 = 'https://covid19.mathdro.id/api/countries'
        response1 = requests.get(url1)
        data1 = response1.json()
        countries_name = data1['countries']
        for i in countries_name:
            try:
                if country_name.title() == i['name'] or country_name.upper() != i['iso2'] or country_name.upper() != i['iso3']:
                    print('***************************************************')
                    print(country_name.upper(),i['name'],i['iso2'],i['iso3'])
                    url2 = 'https://covid19.mathdro.id/api/countries/{}'.format(country_name)
                    response2 = requests.get(url2)
                    data2 = response2.json()
                    confirmed = data2['confirmed']
                    recovered = data2['recovered']
                    deaths = data2['deaths']

                    return render(request,'Results.html',
                    {
                    'country':country_name.upper(),
                    'data':data2,
                    'confirmed_value':confirmed['value'],
                    'recovered_value':recovered['value'],
                    'last_update':data2['lastUpdate'],
                    'death_value':deaths['value'],
                    'confirmed_value_worldwide':confirmed_worldwide['value'],
                    'recovered_value_worldwide':recovered_worldwide['value'],
                    'last_update_worldwide':data_worldwide['lastUpdate'],
                    'death_value_worldwide':deaths_worldwide['value']
                        }
                        )
                
                else:
                    country_name.title()
                    return render(request,'Results.html',
                    {
                    'confirmed_value_worldwide':confirmed_worldwide['value'],
                    'recovered_value_worldwide':recovered_worldwide['value'],
                    'last_update_worldwide':data_worldwide['lastUpdate'],
                    'death_value_worldwide':deaths_worldwide['value']
                        }
                        )
            except:
                return render(request,'Results.html',
                    {
                    
                    'confirmed_value_worldwide':confirmed_worldwide['value'],
                    'recovered_value_worldwide':recovered_worldwide['value'],
                    'last_update_worldwide':data_worldwide['lastUpdate'],
                    'death_value_worldwide':deaths_worldwide['value']
                        }
                        )
        
    return render(request,'index.html',{
            })


pollster/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Question,Choice
from django.http import HttpResponse,JsonResponse
from django.conf.urls import url, include
from django.contrib.auth.models import User
# ###########################################################################
def pollpage(request):
    latestqns=Question.objects.order_by('-pub_date')[:5]
    context={'latestqns':latestqns}
    return render(request,'poll_home.html',context)

def details(request,qn_id):
    qn = get_object_or_404(Question,pk=qn_id)
    return render(request,'poll_details.html',{'qn':qn})

def results(request,qn_id):
    qn = get_object_or_404(Question,pk=qn_id)
    return render(request,'poll_results.html',{'qn':qn})

def vote(request,qn_id):
    qn = get_object_or_404(Question,pk=qn_id)
    try:
        selected_choice = qn.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,'details.html',{'qn':qn,'error':'choice does not exist.Please try again'})
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return redirect('polls:results',qn_id=qn.id)#this is how use pass values in redirect

def resultsdata(request,obj):
    print(obj)
    qn =Question.objects.get(id=obj)
    print(qn)
    votes = qn.choice_set.all()
    votesdata=[]
    for i in votes:
        votesdata.append({i.choice_text:i.votes})
    print(votesdata)
    return JsonResponse(votesdata , safe=False)

templates/Results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stay safe</title>
  <link rel="icon" type="image/png" href="{% static 'mask emoji.png' %}">
  <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'style.css' %}" rel="stylesheet">
  <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand text-danger">
        <img src="{% static 'favicon-32x32.png' %}" width="30" height="30" class="d-inline align-bottom">
        COVID-19
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <a href="{% url 'landingpage:home' %}" class="nav-link btn btn-info btn-sm text-dark">&larr;Back</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <br>
  <div class="container my-5">
{%if country %}
      <h1 class="text-center display-4">{{ country }}</h1>
      <table class="table table-hover table-striped">
        <thead>
            <tr>
              <th>Confirmed Cases</th>
              <th>Death(s)</th>
              <th>Recovered</th>
              <th>Last Update</th>
            </tr>
        </thead>
        <tbody>
            <tr>
              <th>{{ confirmed_value }}</th>
              <td>{{ death_value }}</td>
              <td>{{ recovered_value }}</td>
              <td>{{ last_update }}</td>
            </tr>
        </tbody>
      </table>
{% else %}
<!-- popup using bootstrap (modal) -->
<div class="modal fade" id="overlay">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Result not found</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Please enter a valid country name.Try again</p>
      </div>
    </div>
  </div>
</div>
{% endif %}    
      <h1 class="mt-2 text-center display-4">Statistics WorldWide</h1>
      <table class='table table-hover table-striped'> 
        <thead>
            <tr>
              <th>Confirmed Cases</th>
              <th>Death(s)</th>
              <th>Recovered</th>
              <th>Last Update</th>
            </tr>
        </thead>
        <tbody>
            <tr>
              <th>{{ confirmed_value_worldwide }}</th>
              <td>{{ death_value_worldwide }}</td>
              <td>{{ recovered_value_worldwide }}</td>
              <td>{{ last_update_worldwide }}</td>
            </tr>
        </tbody>
      </table> 
    
 </div>
 <br>
<div class="row">
<div class="col-lg-8 mx-auto">
 <canvas id="myChart" width="100" height="100"></canvas>
</div>
</div>
<!-- Script files -->
<script src="{% static 'jquery.js' %}"></script>
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'bootstrap.js' %}"></script>
<script>
  /*timer value set for 7s */
  $('#overlay').modal('show');
setTimeout(function() {
    $('#overlay').modal('hide');
}, 7000);

/* storing the values */
  var state={
    'items': ['Worldwide cconfirmed','Confirmed cases {{country}}','Worldwide death','death cases {{country}}','Worldwide recovered','recovered cases {{country}}'],
    'values': [ {{confirmed_value_worldwide}},{{ confirmed_value }},{{ death_value_worldwide }},{{ death_value }},{{ recovered_value_worldwide }},{{ recovered_value }}]
}

/* chartjs */
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: state.items,
            datasets: [{
                label: 'No of people',
                data: state.values,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
    


</script>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>  
  <title>Stay safe</title>
  <link rel="icon" type="image/png" href="{% static 'mask emoji.png' %}">
  <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'style.css' %}" rel="stylesheet">
</head>

<body id="page-top">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger text-danger" href="#page-top">
        <img src="{% static 'favicon-32x32.png' %}" width="30" height="30" class="d-inline align-bottom">
        COVID-19
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#search">Statistics</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About us</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-outline-light js-scroll-trigger" href="{% url 'polls:pollpage' %}">Poll</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <header id="showcase">
    <div class="primary-overlay text-white">
      <div class="container">
        <div class="row">
          <div class="py-5 col-lg-12 col-md-8 text-center">
            <h1 class="text-center display-2 mt-5 pt-5"> Corona</h1>
            <p class="text-center lead">The invisible virus has taken control of the whole world.Our nationalities, religion are agnostic to the Coronavirus. The more we unite as fellow beings to address the problem, the earlier we can defeat it.</p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- ***********************home section**************************************** -->
<section id="home">
    <div class="container" style="width:50rem">
            <div class="card bg-dark text-white">
              <div class="card-header text-center">Corona</div>
              <img class="card-img-top" src="{% static 'corona.jpg' %}" alt="...">
              <div class="card-body">
                  <h4 class="card-title">STAY HOME SAVE LIVES</h4>
                  <h6 class="card-subtitle">Help stop coronavirus</h6>
                  <p class="card-text">
                    <ul class="list-group">
                      <li class="list-group-item list-group-item-dark">STAY home</li>
                      <li class="list-group-item list-group-item-dark">KEEP a safe distance</li>
                      <li class="list-group-item list-group-item-dark">WASH hands often</li>
                      <li class="list-group-item list-group-item-dark">COVER your cough</li>
                      <li class="list-group-item list-group-item-dark">SICK? Call the helpline</li>
                    </ul>
                  </p>
              </div>
          </div>
    </div>
</section>
<!-- ***************************Search by frontend for API*********************** -->

  <section id="search" class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 class="text-center">Enter your country name or code</h2>
          <h6 class="text-center text-muted">Get details such as confirmed cases,death(s),recovered...</h6>
          <br>
          <form method="get" name="country" >
                <input  type="search" class="form-control form-control-lg" placeholder="India USA Australia.." name="country" required = required>
                <br>
                <button type="submit" class="btn btn-block btn-lg btn-success">Search</button>
          </form>
        </div>
      </div>
    </div>
  </section>

<!-- **************************************ABOUT section***************************** -->

<section id="about">
  <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 class="text-center mb-3">About us</h2>
          <div class="card-columns">
            <div class="card bg-dark text-white">
                    <img class="card-img-top img-fluid" src="{% static 'wobbly eyes.jpg' %}" alt="sowmiyan">
                    <div class="card-body">
                        <h4 class="card-title">Sowmiyan</h4>
                        <p class="card-text">Second year IT-A TCE</p>   
                    </div>
            </div> 
            <div class="card bg-dark text-white">
                            <img class="card-img-top img-fluid" src="{% static 'wobbly eyes.jpg' %}" alt="ajith">
                           <div class="card-body">
                               <h4 class="card-title">Ajith</h4>
                               <p class="card-text">Second year IT-A TCE</p>           
                           </div>
            </div>
            <div class="card bg-dark text-white">
                <img class="card-img-top img-fluid" src="{% static 'wobbly eyes.jpg' %}" alt="gokul">
                <div class="card-body">
                    <h4 class="card-title">Gokul</h4>
                    <p class="card-text">Second year IT-A TCE</p>
                </div>
            </div>  
            </div>
        </div>
            
    </div>
      </div>
</section>

 
  
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Byte_The_Dust 2020</p>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'jquery.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'jquery.easing.min.js' %}"></script>

  <!-- Custom JavaScript for this theme -->
  <script src="{% static 'scrolling-nav.js' %}"></script>

</body>

</html>

templates/poll_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Vote</title>
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'jquery.easing.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
</head>
<body>
    <!-- nav section -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand text-danger">
            <img src="{% static 'favicon-32x32.png' %}" width="30" height="30" class="d-inline align-bottom">
            COVID-19
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a href="{% url 'polls:pollpage' %}" class="nav-link btn btn-info btn-sm text-dark">&larr;Back to pollpage</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- poll qn -->
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 m-auto">
              <h1 class="text-center mb-3 mt-3">{{ qn.question_text }}</h1>
              {% if  error_message %}
              <p class="alert alert-danger">
                  <strong>{{ error_message }}</strong>
              </p>
              {% endif %}
              <form action="{% url 'polls:vote' qn.id %}" method="POST">
                  {% csrf_token %}
                  {% for choice in qn.choice_set.all %}
                  <div class="form-check">
                      <input type="radio" name="choice" class="form-check-input" id="{{ choice.id }}"value="{{ choice.id }}">
                      <label for="{{ choice.id }}">{{ choice.choice_text }}</label>
                  </div>
                  {% endfor %}
                  <input type="submit" value="Vote" class="btn btn-success btn-lg mt-4 btn-block">
              </form>
            </div>
        </div>  
    </div>
  
 
</body>
</html>




templates/poll_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poll qns</title>
    <link rel="icon" type="image/png" href="{% static 'mask emoji.png' %}">
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand text-danger">
            <img src="{% static 'favicon-32x32.png' %}" width="30" height="30" class="d-inline align-bottom">
            COVID-19
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a href="{% url 'landingpage:home' %}" class="nav-link btn btn-info btn-sm text-dark">&larr;Go to home</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- qn section -->
    {% if latestqns %}
    <h3 class="mt-4 display-3 text-center mt-5">{{ latestqns.count }} Question{{ latestqns.count|pluralize }}</h3>
        {% for qn in latestqns %}
        <div class="container mt-4">
          <div class="row">
            <div class="col-md-6 m-auto">
                <div class="card mb-3 bg-light">
                    <div class="card-body">
                        <p class="lead">{{ qn.question_text }}</p>
                        <a href="{% url 'polls:details' qn.id %}" class="btn btn-primary btn-sm">Vote</a>
                        <a href="{% url 'polls:results' qn.id %}" class="btn btn-secondary btn-sm">Results</a>
                    </div>
                </div>
            </div>
        </div> 
        </div>
    {% endfor %}   
{% else %}
    <p class="display 3">Looks like there are no polls now</p>
{% endif %}
    
</body>
</html>



templates/poll_results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poll results</title>
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'jquery.easing.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand text-danger">
            <img src="{% static 'favicon-32x32.png' %}" width="30" height="30" class="d-inline align-bottom">
            COVID-19
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a href="{% url 'polls:pollpage' %}" class="nav-link btn btn-info btn-sm text-dark">&larr;Back to pollpage</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
<!-- results -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 m-auto">
            <h1 class="text-center mt-2 mb-2">{{ qn.question_text }}</h1>
            <ul class="list-group mb-5">
                {% for choice in qn.choice_set.all %}
                <li class="list-group-item">
                    {{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
                </li>
                {% endfor %}
            </ul>
        <canvas id="myChart" width="400" height="400"></canvas>
        <br>
        <hr style="border-top: 1px dashed black;">
        <a class="btn btn-primary offset-md-2 offset-lg-5" href="{% url 'polls:details' qn.id%}">Vote again!</a>
        </div>
    </div>  
</div>
<br>
<script>
    var state={
        'items': [],
        'values': []
    }
    var obj = "{{qn.id}}"
    console.log(obj)
    var dataurl = `/pollpage/resultsdata/${obj}/` 
    console.log(dataurl)
    $.ajax({
        method:'GET',
        url:dataurl,
        success:function(response){
            console.log('hey there:',response)
            for(var i in response){
                var key=Object.keys(response[i])[0]
                var value=Object.values(response[i])[0]
                state.items.push(key)
                state.values.push(value)
            }
            console.log('state:',state)
            buildChart()
        }
    })
    function buildChart(){
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: state.items,
                datasets: [{
                    label: 'No of Votes',
                    data: state.values,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
        
    }
 
</script>
</body>
</html>
